### ISSUE TITLE
「質問」メール入力チェック

### ISSUE THREAD

**Issue by Zorba-Croooober** [zero-to-yoshino/framework_yoshino#13]
https://github.com/zero-to-yoshino/framework_yoshino/blob/2937190a360be687ce2269bb15589e5816c0ad8b/app/models/User.java#L16

現在登録する時、メール欄のところで「０」で入力でもパスされますが、
メールとうろく入力をチェックする方がいいと思います

**Comment by zero-to-yoshino** [comment]
closeいたします
