### ISSUE TITLE
「エラー」エントリー No Null　無効

### ISSUE THREAD

**Issue by Zorba-Croooober** [zero-to-yoshino/framework_yoshino#14]
https://github.com/zero-to-yoshino/framework_yoshino/blob/2937190a360be687ce2269bb15589e5816c0ad8b/app/models/Entry.java#L18-L25

こちらはNullでもパスされています（最後の２つエントリー）
![Screenshot from 2022-05-25 15-30-16](https://user-images.githubusercontent.com/103471037/170195918-594091cf-a968-43b3-98fc-407a195af25d.png)

**Comment by zero-to-yoshino** [comment]
@Zorba-Croooober 
コメントありがとうございます。まだ検証していないですが、それはNull判定は行っていますが空文字判定はしていないということだと思います。

emailの部分と合わせて入力必須にしていただけると助かります。
