### ISSUE TITLE
「エラー」Errorチェック成立できない

### ISSUE THREAD

**Issue by Zorba-Croooober** [zero-to-yoshino/framework_yoshino#15]
https://github.com/zero-to-yoshino/framework_yoshino/blob/2937190a360be687ce2269bb15589e5816c0ad8b/app/controllers/HomeController.java#L65-L78

こちらのErrorチェックはどうやってもFalseですので、修正すると思います

**Comment by zero-to-yoshino** [comment]
closeいたします
